config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  namespace :admin do
    root to: 'base#index'
    resources :users
    resources :events
  end
  devise_for :users
  resources :users
  resources :events do
    resources :attendances
    resources :event_picture, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :subscription_send
  
  belongs_to :user
  belongs_to :event

  def subscription_send
    event = self.event
    event_admin = event.event_admin
    UserMailer.event_subscription(event_admin, event, user).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true, if: :future_date
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }, if: :multiple_of_five?
  validates :title, presence: true, length: {in: 5..140}
  validates :description, presence: true, length: {in: 20..1000, message: "La description doit faire au moins 20 caratères"}
  validates :price, presence:true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :location, presence: true
  validate :event_picture?

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :event_admin, class_name: "User"

  has_one_attached :event_picture

  def multiple_of_five?
    errors.add(:duration, ": La durée doit être un multiple de 5") unless duration % 5 == 0
  end

  def future_date
    errors.add(:start_date, ": Un événement ne peux pas être dans le passé") unless start_date > DateTime.now
  end

  def is_admin?(user)
    self.event_admin.id == user.id ? true : false
  end

  def is_registred?(user)
    if self.attendances
      self.attendances.find_by(user: user.id) ? true : false
    else 
      puts "n'a pas attendances"
      return
    end
  end

  def event_picture?
    errors.add(:event_picture, ": Veuillez ajouter une photo ") unless self.event_picture.attached? == true

    
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances
  has_many :admin_events, foreign_key: "event_admin_id", class_name: "Event", dependent: :destroy

  has_one_attached :profile_picture

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?

  def index
    @users = User.all
  end
  
  private

  def is_admin?
    unless current_user.is_admin
      redirect_to root_path, danger: "Nope !"
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController

  def index
    @events = Event.where(validated: false)

  end

  def show
    @event = Event.find(params[:id])
    @end_date_time = (@event.start_date + (@event.duration * 60))
  end

  def update
    @event = Event.find(params[:id])  
    if @event.update(validated: true)
      redirect_to root_path, success: "Evénement validé"
    else
      render :edit, alert: "Impossible de valider l'événement :"
    end
    
  end

  def destroy
    @event = Event.find(params[:id]).destroy
    redirect_to root_path, success: "Evénement supprimé !"

  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.all   
  end

  def show
    @user = User.find(params[:id])
    @events = Event.where(event_admin: @user)
  end

  def edit
    @user = User.find(params[:id])
    
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, success: "Profil édité avec succès"
    else
      render :edit, alert: "Impossible d'éditer le profil :"
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to admin_users_path, success: "Profil supprimé avec succès"

  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :profile_picture)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning, :success, :notice, :danger
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!
  before_action :amounts
  before_action :is_admin?, only: [:index]
  before_action :can_subscribe?

  
  def new
  end
  
  def create
  
    begin
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })
      
      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @stripe_amount,
        description: 'Rails Stripe customer',
        currency: 'eur',
        })
        
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_event_attendance_path
    end
    
    Attendance.create(user: current_user, event: @event, stripe_customer_id: customer.id)
  
  end
  
  def index
    @event = Event.find_by(id: params[:event_id])
    @attendances = @event.attendances
    
  end
  
  def can_subscribe?
      @event = Event.find_by(id: params[:event_id])
      if @event.users.select{ |user| user == current_user }.count == 0
        return true
      else
        redirect_to event_path(@event), danger: "Tu es déjà inscrit !"
      end
  end
  
  def is_admin?
      @event = Event.find_by(id: params[:event_id])
      redirect_to root_path unless @event.is_admin?(current_user)
  end

  private
  
  def amounts
    @event = Event.find(params[:event_id])
    @amount = @event.price 
    @stripe_amount = @amount * 100
  end 
  
  
end

app/controllers/event_pictures_controller.rb
class EventPicturesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :edit, :create, :destroy]
  before_action :is_admin?, only: [:edit]

  
  def index
    @events = Event.where(validated: true)
  end

  def show
    @event = Event.find(params[:id])
    @end_date_time = (@event.start_date + (@event.duration * 60))
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.event_admin = current_user
    @event.validated = false

    if @event.save 
      redirect_to event_path(@event.id), success: "Evénement créé avec succès !"
    else
      flash.now[:alert] = " "
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id]).destroy
    redirect_to root_path, success: "Evénement supprimé !"

  end

  def is_admin?
      @event = Event.find_by(id: params[:id])
      redirect_to root_path unless @event.is_admin?(current_user)
  end


  private

  def event_params
    params.require(:event).permit(:title, :start_date, :duration, :description, :price, :location, :event_picture)
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def check_user
     @user = User.find(params[:id])
     unless current_user.id == @user.id
        redirect_to root_path        
     end
  end

  def show
    check_user
    @user = User.find(params[:id])
    @events = Event.where(event_admin: @user)
  end


  def edit
    @user = current_user
    
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), success: "Profile édité"
    else
      flash.now[:alert] = " "
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :profile_picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/event_pictures_helper.rb
module EventPicturesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/base/index.html.erb
<div class="container text-center p-3">
  <%= link_to  "Tous les users", admin_users_path, :class => "btn btn-primary" %>
  <%= link_to  "Tous les events à valider", admin_events_path, :class => "btn btn-primary" %>
</div>

app/views/admin/events/index.html.erb
<div class="row justify-content-center text-center">
  <% @events.each do |event| %>
    <div class="card m-3" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= event.title %></h5>
        <p class="card-text"><%=event.start_date%></p>
        <p class="card-text text-muted"><small>Créé par: <%= event.event_admin.email %></small></p>
        <%= link_to "Page de l'événement", admin_event_path(event.id), :class => "btn btn-outline-primary" %>
        <p>Evénement non validé</p>
        <%= link_to "Valider l'événement", admin_event_path(event.id), method: 'put', :class => "btn btn-outline-success" %>
      </div>
    </div>
  <% end %>

</div>

  

app/views/admin/events/show.html.erb
<div class="container text-center p-2">
  <div class="container text-center p-2">
    <h2 class="p-4"><%= @event.title %></h2>
    <%if @event.event_picture.attached?%>
      <%= image_tag @event.event_picture, alt: 'event picture', id: 'event_picture'%>
    <%else%>
      <p></p>
    <%end%>
  </div>
    
  <div class="container p-2">
    <p><u>Organisateur:</u> <%= @event.event_admin.email %></p>
    <p><u>Ca se passe où ?</u> <%= @event.location%></p>
    <p class="p-2"><u>Description:</u> <%= @event.description %></p>
    <p><u>Ca commence quand ?</u> <%= @event.start_date%> </p>
    <p><u>Ca finit quand ?</u> <%= @end_date_time%> </p>
    <p><u>Son prix:</u> <%= @event.price%> € </p>

    <% if !@event.is_admin?(current_user) && !@event.is_registred?(current_user) %>
        <%= link_to "S'inscrire à l'événement", new_event_attendance_path(@event.id) , class: "btn btn-outline-success"%>
      <% elsif !@event.is_admin?(current_user) && @event.is_registred?(current_user) %>
        <%= link_to "Tu es déjà inscrit", new_event_attendance_path(@event.id) , class: "btn btn-primary"%>
      <% elsif @event.is_admin?(current_user) %>
        <%= link_to "Infos de l'événement", event_attendances_path(@event.id) , class: "btn btn-primary"%>
        <%= link_to "Supprimer l'événement", event_path(@event.id) , class: "btn btn-danger", :method => 'DELETE', :data => {:confirm => "Tu es sûr de vouloir supprimer l'événement?"} %>
        <%= link_to "Valider l'événement", admin_event_path(@event.id), method: 'put', :class => "btn btn-success" %>

    <% end %>

  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for @user, url: admin_user_path(@user), html: { class: "form-signin mt-3" }, multipart: true do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Modifer son profil</h1>
        <div class="form-group">
          <%= f.label :first_name, "Nom" %><br />
          <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, "Nom de famille" %><br />
          <%= f.text_field:last_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Description" %><br />
          <%= f.text_field :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :profile_picture, "Ajouter une photo de profil" %><br />
          <%= f.file_field :profile_picture %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Mettre à jour", class: "btn btn-md btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="row justify-content-center text-center">
    <% @users.each do |user| %>
      <div class="card m-3" style="width: 18rem;">
        <div class="card-body">
          <p class="card-text text-muted">Email: <%= user.email %></p>
          <h5 class="card-title"><%= user.first_name %></h5>
          <p class="card-text"><%=user.last_name%></p>
           <p class="card-text"> <%= link_to "Supprimer l'utilisateur", admin_user_path(user.id) , class: "btn btn-danger", :method => 'DELETE', :data => {:confirm => "Tu es sûr de vouloir supprimer l'utilisateur"} %></p>         
          <p class="card-text"><%= link_to  "Modifier les infos de cet utilisateur", edit_admin_user_path(user.id), :class => "btn btn-primary" %></p>
        </div>
      </div>
    <% end %>
  </div>

  

app/views/attendances/create.html.erb
<div class="container text-center mt-5">
  <h2>Merci, à bientôt</h2>
  <p>Vous avez payé <%=@amount%> € par carte bleue</p>
</div>

app/views/attendances/index.html.erb
<%= render  "shared/attendances" %>

app/views/attendances/new.html.erb
<div class="container text-center mt-5">
  <h2>Inscription à l'événment <u><%=@event.title%></u>, qui commencera le <u><%=@event.start_date%></u></h2>
  <%= form_tag event_attendances_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Prix: <%=@amount%> € </span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="Inscription à l'événement"
      data-amount= <%=@stripe_amount%> 
      data-currency= 'eur'
      data-locale="fr"></script>
  <% end %>
</div>

app/views/event_pictures/create.html.erb
<h1>EventPictures#create</h1>
<p>Find me in app/views/event_pictures/create.html.erb</p>

app/views/events/index.html.erb
<%= render 'shared/jumbotron' %>
<%= render 'shared/events' %>

app/views/events/new.html.erb
<div class="container p-2">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for @event, html: { class: "form-signin mt-3" }, multipart: true do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Créer un événement</h1>
        <div class="form-group">
          <%= f.label :title, "Tire de l'événement" %><br />
          <%= f.text_field :title, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group md">
          <%= f.label :start_date %>
          <%= f.datetime_field :start_date, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :duration, "Durée de l'événement en minutes " %><br />
          <%= f.text_field :duration, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Description de l'événement" %><br />
          <%= f.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price, "Prix de l'événement" %><br />
          <%= f.text_field :price, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :location, "Où va se passer l'événement" %><br />
          <%= f.text_field :location, class: "form-control" %>
        </div>
        <div class="form-group text-center">
          <%= f.label :event_picture, "Ajouter une photo" %><br />
          <%= f.file_field :event_picture %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Créer", class: "btn btn-md btn-primary btn-block", required: true %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<%= render  "shared/show_event" %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg|%>

  <% if @event == nil %>
    <div class="container">
        <div class="text-center alert <%= bootstrap_class_for_flash(type) %> mt-5" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <ul class="list-unstyled">
            <li class="text-center m-3"><%= msg %></li>
          </ul>
        </div>
      </div>
  <% else %>
    <% if @event.errors.any? %>
      <div class="container">
        <div class="alert alert-danger mt-5 " role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <h2 class="text-center">
            <%= I18n.t("errors.messages.not_saved",
                      count: @event.errors.count,
                      resource: @event.class.model_name.human.downcase)
            %>
          </h2>
          <ul class="navbar-nav">
            <% @event.errors.full_messages.each do |message| %>
              <li class="text-center"><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>
  
<%end%>

app/views/layouts/_footer.html.erb
<footer class="footer bg-dark text-center text-white">
  <div class="container-fluid pt-4">
    <div class="row">
      <div class="col-lg-4">
        <ul class="list-unstyled">
          <li><%= link_to "Créer un evenement", new_event_path, class: "text-light" %></li>
          <li><a class="text-light" href="rss/">Contact</a></li>
          <li><a class="text-light" href="https://twitter.com/bootswatch">Twitter</a></li>
          <li><a class="text-light" href="https://github.com/thomaspark/bootswatch">GitHub</a></li>
        </ul>
      </div>
      <div class="col-lg-4">
        <p>Adapté par <a href="#">Arthur RUDY</a></p>
        <p>Créé par <a href="https://thomaspark.co/">Thomas Park</a></p>
        <p>Code released under the <a href="https://github.com/thomaspark/bootswatch/blob/master/LICENSE">MIT License</a></p>
        <p>Basé sur <a href="https://getbootstrap.com/" rel="nofollow">Bootstrap</a> Icons from <a href="https://fontawesome.com/" rel="nofollow">Font Awesome</a> Web fonts from <a href="https://fonts.google.com/" rel="nofollow">Google</a></p>
      </div>
      <div class="col-lg-4">
        <a href="#top" class="text-warning">Retour en haut</a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Eventbrite", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in?%>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <%= link_to "Créer un evenement", new_event_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if current_user.is_admin?%>
            <%= link_to "Dash Admin", admin_root_path, class: "btn btn-outline-danger" %>
          <%end%> 
        </li>
        <li>
          <div class="nav-item dropdown">
            <a class="nav-link btn btn-outline-warning dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Mon profil
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Mon profil", user_path(current_user.id), class: "nav-link btn btn-info mx-2 my-2" %>
              <%= link_to "Se deconnecter", destroy_user_session_path, class: "nav-link btn btn-danger mx-2 my-2", method: "DELETE", data: {confirm: "Êtes-vous sûr ? 😢"} %>
            </div>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <%= link_to "Créer un evenement", new_user_session_path, class: "nav-link" %>
        </li>
      </ul>
      <div class="nav-item dropdown">
        <a class="nav-link btn btn-outline-warning dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          S'inscrire / Se connecter
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link btn btn-outline-warning mx-2 my-2" %>
          <%= link_to "S'inscrire", new_user_registration_path, class: "nav-link btn btn-success mx-2 my-2" %>
        </div>
      </div>    
      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <title>EventbriteLike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/lux/bootstrap.min.css" integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>

    <%= yield %>
    <%= render 'layouts/footer'%> 
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_attendances.html.erb
<div class="container mt-4">
  <h2 class="h3 mb-3 font-weight-normal text-center">La liste des participants pour : <%= @event.title %> </h2>
  <div class="row justify-content-center">
    <% @attendances.each do |attendance| %>
      <div class="card m-3" style="width: 18rem;">
        <div class="card-body">
          <p>First name : <%= attendance.user.first_name %></p>
          <p>Last name : <%= attendance.user.last_name %></p>
          <p>Description : <%= attendance.user.description %></p>
          <p>Email : <%= attendance.user.email %></p>
        </div>
    <% end %>
  </div>
</div>

app/views/shared/_events.html.erb
<div class="container">
  <div class="row justify-content-center text-center">
    <% @events.each do |event| %>
      <div class="card m-3" style="width: 25rem;">
        <div class="card-body">
          <h4 class="card-header"><%= event.title %></h4>
          <%= image_tag  event.event_picture, class: "event_card_img" %>
          <div class="card-body">
            <p class="card-text"><%=event.start_date%></p>
          </div>
          <div class="card-body">
            <p class="card-text"><%=event.description%></p>
          </div>
          <div class="card-body">
            <%= link_to "Page de l'événement", event_path(event.id), :class => "btn btn-outline-primary btn-sm" %>
          </div>
          <div class="card-body">
            <p class="card-text text-muted"><small>Créé par: <%= event.event_admin.email %></small></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_jumbotron.html.erb
<div class="jumbotron jumbotron-img">
  <h1 class="display-4 text-light">Bienvenue !</h1>
  <p class="lead text-light">Viens découvrir les événements de ta ville</p>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <h3 class="indigo-text mb-1 text-center text-white">⏬ Les derniers événements ⏬</h3>

</div>

app/views/shared/_show_event.html.erb
<div class="container mt-4 mb-4">
  <section class="slice slice-lg">
    <div class="container mt-3">
      <div class="row row-grid justify-content-around align-items-center">
        <div class="col-lg-5 order-lg-2">
          <div class=" pr-lg-4">
            <h2 class="p-4"><%= @event.title %></h2>
            <h5><u>Ca commence quand ?</u> <%= @event.start_date%> </h5>
            <h5><u>Ca finit quand ?</u> <%= @end_date_time%> </h5>
            <h5><u>Ca se passe où ?</u> <%= @event.location%> </h5>
            <p><u>Organisateur:</u> <%= @event.event_admin.email %></p>
            <p class="lead mt-3 mb-3"><u>Description:</u> <%= @event.description %></p>
            <h4><u>Son prix:</u> <%= @event.price%> € </h4>

            <% if !@event.is_admin?(current_user) && !@event.is_registred?(current_user) %>
              <%= link_to "S'inscrire à l'événement", new_event_attendance_path(@event.id) , class: "btn btn-outline-success"%>
            <% elsif !@event.is_admin?(current_user) && @event.is_registred?(current_user) %>
              <%= link_to "Tu es déjà inscrit", new_event_attendance_path(@event.id) , class: "btn btn-info"%>
            <% elsif @event.is_admin?(current_user) %>
              <%= link_to "Infos de l'événement", event_attendances_path(@event.id) , class: "btn btn-primary m-1"%>
              <%= link_to "Supprimer l'événement", event_path(@event.id) , class: "btn btn-danger", :method => 'DELETE', :data => {:confirm => "Tu es sûr de vouloir supprimer l'événement?"} %>
            <% end %>
          </div>
        </div>

        <div class="col-lg-6 order-lg-1">
        <%if @event.event_picture.attached?%>
          <%= image_tag @event.event_picture, alt: 'event picture', class: "img-fluid img-center"%>
        <%else%>
          <p></p>
        <%end%>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for @user, html: { class: "form-signin mt-3" }, multipart: true do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Modifer mon profil</h1>
        <div class="form-group">
          <%= f.label :first_name, "Nom" %><br />
          <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, "Nom de famille" %><br />
          <%= f.text_field:last_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Description" %><br />
          <%= f.text_field :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :profile_picture, "Ajouter une photo de profil" %><br />
          <%= f.file_field :profile_picture %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Mettre à jour", class: "btn btn-md btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container p-2">
  <div class="container p-2">
    <div class="container p-2 text-center ">
    <%if @user.profile_picture.attached?%>
      <%= image_tag @user.profile_picture, alt: 'profile_picture', id: 'profile_picture'%>
    <%else%>
      <p>=== Ajoute une photo de profile ! ===</p>
      <%end%>
  </div>

    <ul class="list-group p-2">
      <%= link_to "Editer mes identifiants", edit_user_registration_path(@user), :class => "btn btn-primary" %>
      <li class="list-group-item">Nom : <%=@user.first_name%></li>
      <li class="list-group-item">Prénom : <%=@user.last_name%></li>
      <li class="list-group-item">Email : <%=@user.email%></li>
      <li class="list-group-item">Description : <%=@user.description%></li>
      <%= link_to "Editer mes informations", edit_user_path(@user), :class => "btn btn-primary" %>
    </ul>
  </div>

  <div class="container text-center">
    <h2>Mes événements créés</h2>
    <div class="row justify-content-center">
    <% @events.each do |event| %>
      <div class="card m-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= event.title %></h5>
          <%if event.validated != true%>
            <p>Evénement pas encore accepté</p>
          <%end%>
          <p class="card-text text-muted"><small><%=event.description%></small></p>
          <%= link_to "Infos de l'événement", event_attendances_path(event.id) , class: "btn btn-primary"%>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>